# This is a basic workflow to help you get started with Actions

name: Conditions

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Condition - shell
        run: echo This maps a Jenkins Shell Condition
        if: "${{ echo \"this is executed if it exists\"\ncat \"meow\" }}"
