name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      
    - name: Installing protoc-gen-go
      run: |          
          go get github.com/golang/protobuf/{proto,protoc-gen-go}
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc   
          go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    
    - name: Entering the working directory and Creating pb directory
      run: cd ./src/ResourceMonitor/ && mkdir -p pb

      
    - name: Generating protos
      run: |
          cd ./src/ResourceMonitor/ && make proto

    - name: Build Server    
      run: cd ./src/ResourceMonitor/ && go build -v ./cmd/server/*.go
      
    - name: Build Client    
      run: cd ./src/ResourceMonitor/ && go build -v ./cmd/client/*.go

    - name: Build Misc Items    
      run: cd ./src/ResourceMonitor/ && go build -v ./...

    - name: Test
      run: cd ./src/ResourceMonitor/ && go test -v ./...
